/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION -1
#define MOJOSHADER_CHANGESET "git-12b5fca4faf42d89e19bd9080b1f9877c9b9a7c4"
#endif

