/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION -1
#define MOJOSHADER_CHANGESET "git-cc791ba516115e55155f1fb2c2fba69795cac134"
#endif

